services:
  house_inventory_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_house_inventory:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - house_inventory_db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  db_house_inventory:
  static_volume:
  media_volume: