services:
  house_inventory_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_house_inventory:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - house_inventory_db


volumes:
  db_house_inventory: