# Generated by Django 5.2.1 on 2025-05-18 13:48

import house_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={"ordering": ["apartment_name"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category_name"]},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["item_name"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["room_name"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["tag_name"]},
        ),
        migrations.RenameField(
            model_name="apartment",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="category_id",
            new_name="categories",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="room_id",
            new_name="room",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="apartment_id",
            new_name="apartment",
        ),
        migrations.AddField(
            model_name="item",
            name="photo_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=house_core.models.upload_to_uuid
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="apartment_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="apartment_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="warranty_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="area_m2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="apartment",
            unique_together={("user", "apartment_name")},
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("room", "item_name")},
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("apartment", "room_name")},
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["item_name"], name="house_core__item_na_b5f96c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["model"], name="house_core__model_3a6444_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["brand"], name="house_core__brand_aaffcb_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["purchase_date"], name="house_core__purchas_381609_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["warranty_until"], name="house_core__warrant_9d71db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["created_at"], name="house_core__created_490829_idx"
            ),
        ),
    ]
