# Generated by Django 5.2.1 on 2025-05-27 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house_core", "0002_alter_apartment_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="apartment_description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="apartment_name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Apartment Name"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Purchase Price ₴",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="area_m2",
            field=models.FloatField(blank=True, null=True, verbose_name="Area(m²)"),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_name",
            field=models.CharField(max_length=100, verbose_name="Room Name"),
        ),
    ]
